eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


server:
  port: 8082
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: "covid"
