import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CountryService } from 'app/service/country.service';
import { ActivatedRoute } from '@angular/router';
import { Country } from 'app/service/country';
import { Observable } from 'rxjs';


 

@Component({
  selector: 'app-country-page',
  templateUrl: './country-page.component.html',
  styleUrls: ['./country-page.component.css']
})
export class CountryPageComponent implements OnInit {
  countryFlagMap;
  countryData: Country[];
  filteredCountries: Observable<Country[]>;
  
  constructor(private http: HttpClient,  private route: ActivatedRoute, public countryService: CountryService) { 
    //this.route.params.subscribe(params => console.log(params))
    this.countryFlagMap = new Map ([
      ["Afghanistan", "./assets/countries/Afghanistan.png"],
      ["Albania", "./assets/countries/Albania.png"],
      ["Armenia", "./assets/countries/Armenia.png"],
      ["Andorra", "./assets/countries/Andorra.png"],
      ["Antigua and Barbuda","./assets/countries/antuiga-and-baruda.png"],
      ["Argentina", "./assets/countries/Argentina.png"],
      ["Australia", "./assets/countries/Australia.png"],
      ["Austria", "./assets/countries/Austria.png"],
      ["Azerbaijan", "./assets/countries/Azerbaijan.png"],
      ["Bahamas", "./assets/countries/Bahamas.png"],
      ["Bahrain", "./assets/countries/Bahrain.png"],
      ["Bangladesh", "./assets/countries/Bangladesh.png"],
      ["Belize", "./assets/countries/Belize.png"],
      ["Belarus", "./assets/countries/Belarus.png"],
      ["Belgium", "./assets/countries/Belgium.png"],
      ["Benin", "./assets/countries/Benin.png"],
      ["Bhutan", "./assets/countries/Bhutan.png"],
      ["Bolivia", "./assets/countries/Bolivia.png"],
      ["Bosnia and Herzegovina","./assets/countries/bosnia-and-herzegovina.png"],
      ["Burkina Faso ","./assets/countries/burkina-faso.png"],
      ["Brazil", "./assets/countries/Brazil.png"],
      ["Brunei Darussalam","./assets/countries/brunei.png"],
      ["Bulgaria", "./assets/countries/Bulgaria.png"],
      ["Burundi", "./assets/countries/Burundi.png"],
      ["Cambodia", "./assets/countries/Cambodia.png"],
      ["Cameroon", "./assets/countries/Cameroon.png"],
      ["Canada", "./assets/countries/Canada.png"],
      ["Cape Verde","./assets/countries/cape-verde.png"],
      ["Central African Republic","./assets/countries/central-african-republic.png"],
      ["China", "./assets/countries/China.png"],
      ["Chile", "./assets/countries/Chile.png"],
      ["Colombia", "./assets/countries/Colombia.png"],
      ["Czech Republic", "./assets/countries/czech-republic.png"],
      ["Congo", "./assets/countries/Congo.png"],
      ["Costa Rica","./assets/countries/costa-rica.png"],
      ["Croatia", "./assets/countries/Croatia.png"],
      ["Cuba", "./assets/countries/Cuba.png"],
      ["Cyprus", "./assets/countries/Cyprus.png"],
      ["Côte d'ICôte.pngoire./assets/countries/", "d"],
      ["Denmark", "./assets/countries/Denmark.png"],
      ["Djibouti", "./assets/countries/Djibouti.png"],
      ["Dominica", "./assets/countries/Dominica.png"],
      ["Dominican RepDominican.pngblic./assets/countries/", "d"],
      ["Ecuador", "./assets/countries/Ecuador.png"],
      ["Egypt", "./assets/countries/Egypt.png"],
      ["El SalEl.pngador./assets/countries/", "a"],
      ["Equatorial Guinea","./assets/countries/equatorial-guinea.png"],
      ["Eritrea", "./assets/countries/Eritrea.png"],
      ["Estonia", "./assets/countries/Estonia.png"],
      ["Ethiopia", "./assets/countries/Ethiopia.png"],
      ["Fiji", "./assets/countries/Fiji.png"],
      ["Finland", "./assets/countries/Finland.png"],
      ["France", "./assets/countries/France.png"],
      ["Gabon", "./assets/countries/Gabon.png"],
      ["Gambia", "./assets/countries/Gambia.png"],
      ["Georgia", "./assets/countries/Georgia.png"],
      ["Germany", "./assets/countries/Germany.png"],
      ["Ghana", "./assets/countries/Ghana.png"],
      ["Greece", "./assets/countries/Greece.png"],
      ["Grenada", "./assets/countries/Grenada.png"],
      ["Guatemala","./assets/countries/Guatemala.png"],
      ["Guinea","./assets/countries/Guinea.png"],
      ["Guinea-Bissau", "./assets/countries/guinea-bissau,.png"],
      ["Guyana","./assets/countries/Guyana.png"],
      ["Haiti","./assets/countries/Haiti.png"],
      ["Holy See (Vatican City State)", " ./assets/countries/vatican-city.png"],
      ["Honduras","./assets/countries/Honduras.png"],
      ["Hungary","./assets/countries/Hungary.png"],
      ["Iceland","./assets/countries/Iceland.png"],
      ["India","./assets/countries/India.png"],
      ["Indonesia","./assets/countries/Indonesia.png"],
      ["Iran, Islamic Republic of","./assets/countries/iran.png"],
      ["Iraq","./assets/countries/Iraq.png"],
      ["Ireland","./assets/countries/Ireland.png"],
      ["Israel","./assets/countries/Israel.png"],
      ["Italy","./assets/countries/Italy.png"],
      ["Jamaica","./assets/countries/Jamaica.png"],
      ["Japan","./assets/countries/Japan.png"],
      ["Jordan","./assets/countries/Jordan.png"],
      ["Kazakhstan","./assets/countries/Kazakhstan.png"],
      ["Kenya","./assets/countries/Kenya.png"],
      ["Kuwait","./assets/countries/Kuwai.png"],
      ["Kyrgyzstan","./assets/countries/Kyrgyzstan.png"],
      ["Lao PDR","./assets/countries/laos.png"],
      ["Latvia","./assets/countries/Latvia.png"],
      ["Lebanon","./assets/countries/Lebanon.png"],
      ["Lesotho","./assets/countries/Lesotho.png"],
      ["Liberia","./assets/countries/Liberia.png"],
      ["Libya","./assets/countries/Libya.png"],
      ["Liechtenstein","./assets/countries/Liechtenstein.png"],
      ["Lithuania","./assets/countries/Lithuania.png"],
      ["Luxembourg","./assets/countries/Luxembourg.png"],
      ["Madagascar","./assets/countries/Madagascar.png"],
      ["Malawi","./assets/countries/Malawi.png"],
      ["Malaysia","./assets/countries/Malaysia.png"],
      ["Maldives","./assets/countries/Maldives.png"],
      ["Mali","./assets/countries/Mali.png"],
      ["Malta","./assets/countries/Malta.png"],
      ["Mauritania","./assets/countries/Mauritania.png"],
      ["Mauritius","./assets/countries/Mauritius.png"],
      ["Mexico","./assets/countries/Mexico.png"],
      ["Moldova","./assets/countries/Moldova.png"],
      ["Monaco","./assets/countries/Monaco.png"],
      ["Mongolia","./assets/countries/Mongoli.png"],
      ["Montenegro","./assets/countries/Montenegro.png"],
      ["Morocco","./assets/countries/Morocco.png"],
      ["Mozambique","./assets/countries/Mozambique.png"],
      ["Myanmar","./assets/countries/Myanmar.png"],
      ["Namibia","./assets/countries/Namibia.png"],
      ["Nepal","./assets/countries/Nepal.png"],
      ["Netherlands","./assets/countries/Netherlands.png"],
      ["New Zealand", "./assets/countries/new-zealand.png"],
      ["Nicaragua","./assets/countries/Nicaragua.png"],
      ["Niger","./assets/countries/Niger.png"],
      ["Nigeria","./assets/countries/Nigeria.png"],
      ["Norway","./assets/countries/Norwa<.png"],
      ["Oman","./assets/countries/Oman.png"],
      ["Pakistan","./assets/countries/Pakistan.png"],
      ["Palestinian Territory", "./assets/countries/palestine.png"],
      ["Panama","./assets/countries/Panama.png"],
      ["Papua New Guinea", "./assets/countries/paua-new-guinea.png"],
      ["Paraguay","./assets/countries/Paraguay.png"],
      ["Peru","./assets/countries/Peru.png"],
      ["Philippines","./assets/countries/Philippine.png"],
      ["Poland","./assets/countries/Poland.png"],
      ["Portugal","./assets/countries/Portugal.png"],
      ["Qatar","./assets/countries/Qatar.png"],
      ["Republic of Kosovo", "./assets/countries/kosovo.png"],
      ["Romania","./assets/countries/Romania.png"],
      ["Russian Federation", "./assets/countries/russia.png"],
      ["Rwanda","./assets/countries/Rwanda.png"],
      ["Saint Kitts and Nevis", "./assets/countries/saint/kitts-and-nevis.png"],
      ["San Marino","./assets/countries/san-marino.png"],
      ["Sao Tome and Principe", "./assets/countries/sao-tome-and-principe.png"],
      ["Saudi Arabia","./assets/countries/saudi-arabia.png"],
      ["Senegal","./assets/countries/Senegal.png"],
      ["Serbia","./assets/countries/Serbia.png"],
      ["Seychelles","./assets/countries/Seychelles.png"],
      ["Sierra Leone", "./assets/countries/sierra-leone.png"],
      ["Singapore","./assets/countries/Singapore.png"],
      ["Slovakia","./assets/countries/Slovakia.png"],
      ["Slovenia","./assets/countries/Slovenia.png"],
      ["Somalia","./assets/countries/Somalia.png"],
      ["South Africa", "./assets/countries/south-africa.png"],
      ["South Sudan", "./assets/countries/south-sudan.png"],
      ["Spain","./assets/countries/Spain.png"],
      ["Sri Lanka", "./assets/countries/sri-lanka.png"],
      ["Sudan","./assets/countries/Sudan.png"],
      ["Suriname","./assets/countries/Suriname.png"],
      ["Swaziland","./assets/countries/Swazilan"],
      ["Sweden","./assets/countries/Sweden.png"],
      ["Switzerland","./assets/countries/Switzerland.png"],
      ["Syrian Arab Republic (Syria)","./assets/countries/Syria.png"],
      ["Taiwan, Republic of China", "./assets/countries/taiwan"],
      ["Tajikistan","./assets/countries/tajikistan.png"],
      ["Tanzania, United Republic of","./assets/countries/tanzania.png"],
      ["Thailand","./assets/countries/thailand.png"],
      ["Togo","./assets/countries/togo.png"],
      ["Trinidad and Tobago", "./assets/countries/trinidad-and-tobago.png"],
      ["Tunisia","./assets/countries/Tunisi"],
      ["Turkey","./assets/countries/Turke"],
      ["Uganda","./assets/countries/Ugand"],
      ["Ukraine","./assets/countries/Ukrain"],
      ["United Arab Emirates", "./assets/countries/united-arab-emirates"],
      ["United Kingdom", "./assets/countries/united-kingdom"],
      ["United States of America", "./assets/countries/united-states-of-america"],
      ["Uruguay","./assets/countries/Urugua"],
      ["Uzbekistan","./assets/countries/uzbekistn"],
      ["Venezuela", "./assets/countries/venezuela"],
      ["Viet Nam", "./assets/countries/vietman"],
      ["Western Sahara", "./assets/countries/western-sahara.png"],
      ["Yemen","./assets/countries/yemen.png"],
      ["Zambia","./assets/countries/Zambia.png"],
      ["Zimbabwe","./assets/countries/Zimbabwe.png"],

      ]);
      this.countryService.getCountries().subscribe((data) => { this.countryData; })
     
  
  }


  ngOnInit(): void {}

}
